# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alarm',
            new_name='Alert',
        ),
        migrations.AddField(
            model_name='trigger',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_config_app.Alert'),
        ),
    ]
