# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0007_auto_20170714_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvname',
            old_name='post',
            new_name='PV_Name',
        ),
    ]
