# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0008_auto_20170714_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PVname',
        ),
    ]
