# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0009_delete_pvname'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_lockout',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
