# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0010_auto_20170810_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_last_sent',
            new_name='last_sent',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_lockout',
            new_name='lockout_duration',
        ),
    ]
