# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_config_app', '0011_auto_20170810_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='pv',
        ),
        migrations.AddField(
            model_name='trigger',
            name='value_src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
